---
title: "Mini-Project 3"
author: "Jemimah Charles, Maria de Villeneuve, Vanessa Simplice :)"
date: "April 15, 2018"
output: 
 html_document:
    code_folding: hide
---
## Oh no! A big, perfect space for camping! We can't go over it, we can't go under it, we gotta stay in it! 

For Mini Project 3, our group decided to work on topic number 3 to find options for new campsites at Macleish Field Station using a GitHub Repository[^1]. We started by mapping out all the different requirements for an ideal campsite to see where the requirements overlapped and where the vegetation was “building friendly”. As for the data, we used the vegetation type shapefile, the existing trails shapefile, contour elevation data, research and challenge course locations shapefile, the location of the established campsites and parking lot and property boundary shapefile. We believe the campsites would cost about 359 USD.This would be considering an approximate price for the wood for the base at approximately 180 USD (the plywood cost 5x8 at 31 USD a piece and the blocks cost 1.89 USD )[^2], a wooden picnic table at around 179 USD[^3] and the manual labor being on a volunteer base, and the fire pit being built out of donated or reclaimed stones found around the Macleish field station. Additionally, there will be the cost of removing the existing vegetation which depends on the location of the campsite but we choose locations where the vegetation isn’t considered too difficult. Our map is also geared towards showing campers the best secluded spots away from noise and other people/scientists/students/campers which are represented by the red areas. 
	Our main idea was that we would like to make Macleish more accessible to everyone and not simply designed for the engineers or environmentalist who usually use the facilities. We want to allow older people or people with disabilities to have a camping experience without having to hike a trail, as well as making hiking and camping more beginner friendly. As much as hiking can be healthy, it isn’t accessible to everyone. Most seniors aren’t capable of hiking several miles with backpacks carrying enough for a night’s stay. Children might be difficult to take if a lot of hiking is necessary to reach a campsite and anyone with physical disabilities would not have the opportunity to camp. Additionally, anyone with medical concerns should be able to have access to an ambulance if necessary. As the campsites are either right next to the entrance of the parking lot or in an open field, a gurney or the ambulance would be able to get to them. 
We wanted to place our first campsite near the parking lot. If the campsite was placed near the parking lot, it would only be a short walking distance to the campsite, welcoming all different types of people to be able to camp at Macleish. Additionally, it would definitely make it make it accessible to a stretcher if needed for any medical concerns. We believe this campsite location would also have to include the cost of an insect net since it is close to water which would cost up to $150. We have however made sure that it is far enough from the water avoiding any flooding risks. As this is in a forest, this campsite could take several weeks to build. Trees may have to be cut down, which will take time to decide which trees must be cut down. This is a slight environmental impact, because they might be home to birds, insects and rodents. This would be the only roadblock. Otherwise, as it is close enough to the parking lot, it wouldn’t be too challenging to move the building materials to the campsite. 
For our second campsite, we chose a flat area which makes it easy to build and access. This campsite would also make Macleish more welcoming as a whole as the area is very flat and enables small peaceful walks without too much effort. It would also allow people who might be scared of the woods and adventuring too far down a hiking path to be able to enjoy nature in a place it may seem less threatening. As it is in a clearing, it would be easily visible for those who have difficulty seeing. An additional flag could be put up in the camping area in order to make it even more visible. This could be done very inexpensively. This campsite would also have a low environmental impact, because no trees would need to be cleared to create the campsite. As it is in a clearing, this campsite should take less than 4 days to create, depending on the amount of volunteers and clear weather. 
	We recommend Smith use these findings in order to create a more accessible and all-welcoming Macleish, allowing all types of people to enjoy the beautiful fields and have a safe camping experience. 

Word Count: 768


[^1]: https://github.com/jemimahcharles/sds192-mini3.git
[^2]: https://www.homedepot.com/b/Lumber-Composites-Plywood/1-2/N-5yc1vZbqm7Z1z0mcqn
[^3]: https://www.uline.com/Product/Detail/H-2999/Outdoor-Furniture-and-Equipment/Economy-A-Frame-Wooden-Picnic-Table-6?pricode=WA9499&gadtype=pla&id=H-2999&gclid=EAIaIQobChMIq4_ElO292gIVRwOGCh1PGQuCEAYYASABEgKDlfD_BwE&gclsrc=aw.ds 

```{r setup, include=TRUE, warning = FALSE, message = FALSE}
library(tidyverse)
library(macleish)
library(leaflet)
library(sf)
library(rgdal)
library(htmltools)
library(sp)
library(rgeos)

#computing the lenght of the streams to fit the map's geometry
trails <- macleish_layers[["streams"]] %>%
  mutate(computed_length = st_length(geometry))

#Make a color set based on the different forest types in the macleish layer of forest
forest_pal <- colorFactor("Greens", macleish_layers[["forests"]]$Sheet1__Ve)

#Buffers for Streams, Wetlands, Research, Challenge courses
stream_buffer <- macleish_layers[["streams"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 60.96) %>%
  st_transform(4326)

wet_buffer <- macleish_layers[["wetlands"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 60.96) %>%
  st_transform(4326)

research_buffer <- macleish_layers[["research"]]%>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 152.4) %>%
  st_transform(4326)

challenge_buffer <- macleish_layers[["challenge_courses"]]%>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 152.4) %>%
  st_transform(4326)

#Old campsites' coordinate
group_camp <- data.frame(lat =42.450976, lon = -72.678154)
remote_camp <- data.frame(lat = 42.458549, lon = -72.679581)

#new data frame for parking lot's coordinates
example_points <- data.frame(lat = numeric(), long = numeric())
example_points[1,] <- c(42.448013, -72.680663)
coordinates(example_points) <- (~long + lat)

#buffer for parking lot
pointsBuffer <- gBuffer(example_points, width= .008, byid = TRUE, capStyle="ROUND", joinStyle="ROUND")

#new data set for new 
camp_points <- data.frame(lat = numeric(), long = numeric())
camp_points[1,] <- c(42.448963, -72.682359)
camp_points[2,] <- c(42.447396, -72.679648)
coordinates(camp_points) <- (~long + lat)

#Computing projects of map
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

#Converting the boundry of Macleish for the map
boundaries_aea <- macleish_layers[["boundary"]] %>%
  st_transform(proj4_aea)

#Map of new camp sites
new_camps<- leaflet() %>%
  # Base groups
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles("Esri.WorldTopoMap", group = "Topography") %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite") %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite") %>%
  # Boundaries
  #Forest is outlined by different shades of green, based on different forest type
  addPolygons(data = macleish_layers[["forests"]], 
              weight = 1, color = ~forest_pal(Sheet1__Ve), fillOpacity = 0.85, popup = ~ Sheet1__Na, group = "Forest") %>%
  #Research and Challenge Courses' buffers are not completely shaded in order to show the forest lines and topography lines
  addPolygons(data = research_buffer, fillOpacity = .15, color = "brown", weight = 1, group = "Research") %>%
  addPolygons(data = challenge_buffer, fillOpacity = .15, color = "red", weight = 1, group = "Challenge") %>%
  #Streams line is blue to symbolize water and its buffer is the same. It is not shaded in because it is still an area that can be used for the new campsite. 
  addPolylines(data = macleish_layers[["streams"]], color = "blue", group = "Streams")%>%
  addPolygons(data = stream_buffer, fillOpacity = 0, weight = 1, group = "Streams") %>%
  #Wetlands buffer and area are blue to sybmobolize water. It is also not shaded in because it is an area still capable of having a camp ground. 
  addPolygons(data = macleish_layers[["wetlands"]], 
              weight = 1, group = "Wetlands") %>%
  addPolygons(data = wet_buffer, fillOpacity = 0, weight = 1, group = "Wetlands") %>%
  #Trails are in black in order to see easier
  addPolylines(data = macleish_layers[["trails"]], color = "black", group = "Trails")%>%
  #Buildings are also in black with their name attacked to see clearly which they are. 
  addPolygons(data = macleish_layers[["buildings"]], 
              weight = 1, popup = ~ name, color ="black", group = "Buildings") %>%
  #Research is in organge to show an area should be preceeded into with caution
  addPolylines(data = macleish_layers[["research"]], color = "Orange", group = "Research")%>%
  #Challenge Courses
  addMarkers(data=macleish_layers[["challenge_courses"]], popup = ~geometry, label = "Challenge Course", group = "Challenge") %>%
  #Old camp site markers
  addMarkers(lng = ~lon, lat = ~lat, data = remote_camp, popup = "Remote Campsite") %>%
  addMarkers(lng = ~lon, lat = ~lat, data = group_camp, popup = "Group Campsite") %>%
  #Parking lot is outlined in yellow, because yellow is a welcoming color and will stand out against the other colors. 
  addMarkers(data=example_points, label = "Parking Lot")%>%
  addPolygons(data=pointsBuffer, fillOpacity = 0, weight = .75, group = "Parking Lot Boundary", color = "yellow")%>%
  #New camps
  addMarkers(data=camp_points, label = c("Camp 1", "Camp 2"))%>%
  #Topography of macleish. It is outlined in purple to stand out against the other colors, without drawing focus to it. 
  addPolylines(data=macleish_layers[["contours_30ft"]], weight = 3, color = "purple", group = "Topography of Macleish")%>%
  # Layers control
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Topography", "Satellite", "Toner Lite"),
    overlayGroups = c("Streams","Trails", "Wetlands", "Research", "Challenge", "Topography of Macleish", "Forest", "Parking Lot Boundary"),
    options = layersControlOptions(collapsed = FALSE)
  )

#Call map
new_camps
```